/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminAiAnalyticsRouteImport } from './routes/admin.ai-analytics'
import { Route as DashboardStudyPlanRouteImport } from './routes/_dashboard.study-plan'
import { Route as DashboardProgressRouteImport } from './routes/_dashboard.progress'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard.profile'
import { Route as DashboardMyQuestionsRouteImport } from './routes/_dashboard.my-questions'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardAiTutorRouteImport } from './routes/_dashboard.ai-tutor'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as DashboardTestIndexRouteImport } from './routes/_dashboard.test.index'
import { Route as DashboardExamsIndexRouteImport } from './routes/_dashboard.exams.index'
import { Route as DashboardTestSetupRouteImport } from './routes/_dashboard.test.setup'
import { Route as DashboardTestSessionIdRouteImport } from './routes/_dashboard.test.$sessionId'
import { Route as DashboardStudyTopicIdRouteImport } from './routes/_dashboard.study.$topicId'
import { Route as DashboardExamsExamIdRouteImport } from './routes/_dashboard.exams.$examId'
import { Route as DashboardTestSessionIdResultsRouteImport } from './routes/_dashboard.test.$sessionId.results'
import { Route as DashboardTestSessionIdResultRouteImport } from './routes/_dashboard.test.$sessionId.result'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAnalyticsRoute = AdminAiAnalyticsRouteImport.update({
  id: '/ai-analytics',
  path: '/ai-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardStudyPlanRoute = DashboardStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyQuestionsRoute = DashboardMyQuestionsRouteImport.update({
  id: '/my-questions',
  path: '/my-questions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiTutorRoute = DashboardAiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardTestIndexRoute = DashboardTestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamsIndexRoute = DashboardExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestSetupRoute = DashboardTestSetupRouteImport.update({
  id: '/test/setup',
  path: '/test/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestSessionIdRoute = DashboardTestSessionIdRouteImport.update({
  id: '/test/$sessionId',
  path: '/test/$sessionId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudyTopicIdRoute = DashboardStudyTopicIdRouteImport.update({
  id: '/study/$topicId',
  path: '/study/$topicId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamsExamIdRoute = DashboardExamsExamIdRouteImport.update({
  id: '/exams/$examId',
  path: '/exams/$examId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestSessionIdResultsRoute =
  DashboardTestSessionIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => DashboardTestSessionIdRoute,
  } as any)
const DashboardTestSessionIdResultRoute =
  DashboardTestSessionIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => DashboardTestSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/ai-tutor': typeof DashboardAiTutorRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/my-questions': typeof DashboardMyQuestionsRoute
  '/profile': typeof DashboardProfileRoute
  '/progress': typeof DashboardProgressRoute
  '/study-plan': typeof DashboardStudyPlanRoute
  '/admin/ai-analytics': typeof AdminAiAnalyticsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/exams/$examId': typeof DashboardExamsExamIdRoute
  '/study/$topicId': typeof DashboardStudyTopicIdRoute
  '/test/$sessionId': typeof DashboardTestSessionIdRouteWithChildren
  '/test/setup': typeof DashboardTestSetupRoute
  '/exams/': typeof DashboardExamsIndexRoute
  '/test/': typeof DashboardTestIndexRoute
  '/test/$sessionId/result': typeof DashboardTestSessionIdResultRoute
  '/test/$sessionId/results': typeof DashboardTestSessionIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/ai-tutor': typeof DashboardAiTutorRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/my-questions': typeof DashboardMyQuestionsRoute
  '/profile': typeof DashboardProfileRoute
  '/progress': typeof DashboardProgressRoute
  '/study-plan': typeof DashboardStudyPlanRoute
  '/admin/ai-analytics': typeof AdminAiAnalyticsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/exams/$examId': typeof DashboardExamsExamIdRoute
  '/study/$topicId': typeof DashboardStudyTopicIdRoute
  '/test/$sessionId': typeof DashboardTestSessionIdRouteWithChildren
  '/test/setup': typeof DashboardTestSetupRoute
  '/exams': typeof DashboardExamsIndexRoute
  '/test': typeof DashboardTestIndexRoute
  '/test/$sessionId/result': typeof DashboardTestSessionIdResultRoute
  '/test/$sessionId/results': typeof DashboardTestSessionIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_dashboard/ai-tutor': typeof DashboardAiTutorRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/my-questions': typeof DashboardMyQuestionsRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/progress': typeof DashboardProgressRoute
  '/_dashboard/study-plan': typeof DashboardStudyPlanRoute
  '/admin/ai-analytics': typeof AdminAiAnalyticsRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_dashboard/exams/$examId': typeof DashboardExamsExamIdRoute
  '/_dashboard/study/$topicId': typeof DashboardStudyTopicIdRoute
  '/_dashboard/test/$sessionId': typeof DashboardTestSessionIdRouteWithChildren
  '/_dashboard/test/setup': typeof DashboardTestSetupRoute
  '/_dashboard/exams/': typeof DashboardExamsIndexRoute
  '/_dashboard/test/': typeof DashboardTestIndexRoute
  '/_dashboard/test/$sessionId/result': typeof DashboardTestSessionIdResultRoute
  '/_dashboard/test/$sessionId/results': typeof DashboardTestSessionIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ai-tutor'
    | '/dashboard'
    | '/my-questions'
    | '/profile'
    | '/progress'
    | '/study-plan'
    | '/admin/ai-analytics'
    | '/admin/exams'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/exams/$examId'
    | '/study/$topicId'
    | '/test/$sessionId'
    | '/test/setup'
    | '/exams/'
    | '/test/'
    | '/test/$sessionId/result'
    | '/test/$sessionId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ai-tutor'
    | '/dashboard'
    | '/my-questions'
    | '/profile'
    | '/progress'
    | '/study-plan'
    | '/admin/ai-analytics'
    | '/admin/exams'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/exams/$examId'
    | '/study/$topicId'
    | '/test/$sessionId'
    | '/test/setup'
    | '/exams'
    | '/test'
    | '/test/$sessionId/result'
    | '/test/$sessionId/results'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/admin'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_dashboard/ai-tutor'
    | '/_dashboard/dashboard'
    | '/_dashboard/my-questions'
    | '/_dashboard/profile'
    | '/_dashboard/progress'
    | '/_dashboard/study-plan'
    | '/admin/ai-analytics'
    | '/admin/exams'
    | '/admin/questions'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/_dashboard/exams/$examId'
    | '/_dashboard/study/$topicId'
    | '/_dashboard/test/$sessionId'
    | '/_dashboard/test/setup'
    | '/_dashboard/exams/'
    | '/_dashboard/test/'
    | '/_dashboard/test/$sessionId/result'
    | '/_dashboard/test/$sessionId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-analytics': {
      id: '/admin/ai-analytics'
      path: '/ai-analytics'
      fullPath: '/admin/ai-analytics'
      preLoaderRoute: typeof AdminAiAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_dashboard/study-plan': {
      id: '/_dashboard/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof DashboardStudyPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/progress': {
      id: '/_dashboard/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/my-questions': {
      id: '/_dashboard/my-questions'
      path: '/my-questions'
      fullPath: '/my-questions'
      preLoaderRoute: typeof DashboardMyQuestionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ai-tutor': {
      id: '/_dashboard/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof DashboardAiTutorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/test/': {
      id: '/_dashboard/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof DashboardTestIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/exams/': {
      id: '/_dashboard/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof DashboardExamsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/test/setup': {
      id: '/_dashboard/test/setup'
      path: '/test/setup'
      fullPath: '/test/setup'
      preLoaderRoute: typeof DashboardTestSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/test/$sessionId': {
      id: '/_dashboard/test/$sessionId'
      path: '/test/$sessionId'
      fullPath: '/test/$sessionId'
      preLoaderRoute: typeof DashboardTestSessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/study/$topicId': {
      id: '/_dashboard/study/$topicId'
      path: '/study/$topicId'
      fullPath: '/study/$topicId'
      preLoaderRoute: typeof DashboardStudyTopicIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/exams/$examId': {
      id: '/_dashboard/exams/$examId'
      path: '/exams/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof DashboardExamsExamIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/test/$sessionId/results': {
      id: '/_dashboard/test/$sessionId/results'
      path: '/results'
      fullPath: '/test/$sessionId/results'
      preLoaderRoute: typeof DashboardTestSessionIdResultsRouteImport
      parentRoute: typeof DashboardTestSessionIdRoute
    }
    '/_dashboard/test/$sessionId/result': {
      id: '/_dashboard/test/$sessionId/result'
      path: '/result'
      fullPath: '/test/$sessionId/result'
      preLoaderRoute: typeof DashboardTestSessionIdResultRouteImport
      parentRoute: typeof DashboardTestSessionIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardTestSessionIdRouteChildren {
  DashboardTestSessionIdResultRoute: typeof DashboardTestSessionIdResultRoute
  DashboardTestSessionIdResultsRoute: typeof DashboardTestSessionIdResultsRoute
}

const DashboardTestSessionIdRouteChildren: DashboardTestSessionIdRouteChildren =
  {
    DashboardTestSessionIdResultRoute: DashboardTestSessionIdResultRoute,
    DashboardTestSessionIdResultsRoute: DashboardTestSessionIdResultsRoute,
  }

const DashboardTestSessionIdRouteWithChildren =
  DashboardTestSessionIdRoute._addFileChildren(
    DashboardTestSessionIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAiTutorRoute: typeof DashboardAiTutorRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardMyQuestionsRoute: typeof DashboardMyQuestionsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardStudyPlanRoute: typeof DashboardStudyPlanRoute
  DashboardExamsExamIdRoute: typeof DashboardExamsExamIdRoute
  DashboardStudyTopicIdRoute: typeof DashboardStudyTopicIdRoute
  DashboardTestSessionIdRoute: typeof DashboardTestSessionIdRouteWithChildren
  DashboardTestSetupRoute: typeof DashboardTestSetupRoute
  DashboardExamsIndexRoute: typeof DashboardExamsIndexRoute
  DashboardTestIndexRoute: typeof DashboardTestIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiTutorRoute: DashboardAiTutorRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardMyQuestionsRoute: DashboardMyQuestionsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardStudyPlanRoute: DashboardStudyPlanRoute,
  DashboardExamsExamIdRoute: DashboardExamsExamIdRoute,
  DashboardStudyTopicIdRoute: DashboardStudyTopicIdRoute,
  DashboardTestSessionIdRoute: DashboardTestSessionIdRouteWithChildren,
  DashboardTestSetupRoute: DashboardTestSetupRoute,
  DashboardExamsIndexRoute: DashboardExamsIndexRoute,
  DashboardTestIndexRoute: DashboardTestIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminAiAnalyticsRoute: typeof AdminAiAnalyticsRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiAnalyticsRoute: AdminAiAnalyticsRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
